version: '3.6'

services:
  jupyter:
    image: bamcis/jupyter-alpine:latest
    container_name: jupyter
    environment:
      ROLE: notebook
    ports:
    - 8888:8888
    - 8081:8081
    networks:
    - default