FROM bamcis/ca-debian:latest

MAINTAINER Michael Haken <michael.haken@outlook.com>

SHELL ["/bin/bash", "-c"]

ARG JUPYTER_PATH="/opt/jupyter"
ARG JUPYTER_CONFIG_DIR="/opt/jupyter/etc"
ARG VERSION="5.5"

ENV DEBIAN_FRONTEND="noninteractive" \
	CONDA_DIR=/opt/conda \
	PATH="/opt/conda/bin:${PATH}" \
	MINICONDA_VERSION=4.5.1 \
	JUPYTER_PATH="${JUPYTER_PATH}" \
	JUPYTER_CONFIG_DIR="${JUPYTER_CONFIG_DIR}" \
	ROLE="notebook"

RUN apt-get update \
	&& apt-get -y upgrade \
	&& apt-get remove --assume-yes ^openjdk \
	&& apt-get install --assume-yes \
	build-essential \
	libncurses5-dev \
	libncursesw5-dev \
	libzmq3-dev \
	wget \
	&& mkdir -p $JUPYTER_PATH \
	&& mkdir -p $JUPYTER_CONFIG_DIR \
	&& echo "export JUPYTER_PATH=${JUPYTER_PATH}" > /etc/profile.d/jupyter.sh \
	&& echo "export JUPYTER_CONFIG_DIR=${JUPYTER_CONFIG_DIR}" >> /etc/profile.d/jupyter.sh \
	#
	# Download and install miniconda3
	#
	&& wget --quiet --directory-prefix "/tmp/" "https://repo.continuum.io/miniconda/Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh" \
	&& /bin/bash "/tmp/Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh" -f -b -p $CONDA_DIR \
	&& rm "/tmp/Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh" \
	&& $CONDA_DIR/bin/conda config --system --prepend channels conda-forge \
    && $CONDA_DIR/bin/conda config --system --set auto_update_conda false \
    && $CONDA_DIR/bin/conda config --system --set show_channel_urls true \
    && $CONDA_DIR/bin/conda update --all --quiet --yes \
    && conda clean -tipsy \
    && rm -rf /root/.cache/yarn \
	#
	# Install jupyter notebook
	#
	&& conda install --quiet --yes \
	"notebook=${VERSION}.*" \
	'jupyterhub=0.8.*' \
    'jupyterlab=0.32.*' \
	'scipy' \
	'numpy' \
	'matplotlib' \
	&& conda clean -tipsy \
    && jupyter labextension install @jupyterlab/hub-extension \
	&& pip install --upgrade pip \
    && npm cache clean --force \
    && rm -rf $CONDA_DIR/share/jupyter/lab/staging \
    && rm -rf /root/.cache/yarn \
	#
	# Setup the JupyterHub config
	#
	&& mkdir -p /etc/jupyterhub \
	&& jupyterhub --generate-config -f /etc/jupyterhub/jupyterhub_config.py \
	#
	# Add admin user to JupyterHub
	#
	&& echo "c.Authenticator.admin_users = {'jupyter'}" >> /etc/jupyterhub/jupyterhub_config.py \
	#
	# Create local users automatically when a hub admin creates them
	#
	&& echo "c.LocalAuthenticator.create_system_users = True" >> /etc/jupyterhub/jupyterhub_config.py \
	#
	# Peform cert setup
	#
	# The Server certificate request
	#
	&& mkdir -p ${JUPYTER_PATH}/ssl \
	&& touch  ${JUPYTER_PATH}/ssl/server.req \
	&& echo [ req ] >>  ${JUPYTER_PATH}/ssl/server.req \
	&& echo prompt				= no >> ${JUPYTER_PATH}/ssl/server.req \
	&& echo default_bits		= 2048 >> ${JUPYTER_PATH}/ssl/server.req \
	&& echo distinguished_name	= req_distinguished_name >> ${JUPYTER_PATH}/ssl/server.req \
	&& echo req_extensions		= req_ext >> ${JUPYTER_PATH}/ssl/server.req \
	&& echo default_md			= sha_256 >> ${JUPYTER_PATH}/ssl/server.req \
	#
	# Extension to add when the -x509 option is used.
	#
	&& echo x509_extensions     = server_cert >> ${JUPYTER_PATH}/ssl/server.req \
	&& echo [ req_distinguished_name ] >> ${JUPYTER_PATH}/ssl/server.req \
	&& echo O					= bamcis.io >> ${JUPYTER_PATH}/ssl/server.req \
	&& echo OU					= bamcis-jupyter-notebook >> ${JUPYTER_PATH}/ssl/server.req \
	&& echo CN					= ${HOSTNAME} >> ${JUPYTER_PATH}/ssl/server.req \
	&& echo [ server_cert ] >> ${JUPYTER_PATH}/ssl/server.req \
	#
	# Extensions for server certificates (man x509v3_config).
	#
	&& echo basicConstraints	= CA:FALSE >> ${JUPYTER_PATH}/ssl/server.req \
	&& echo nsCertType			= server >> ${JUPYTER_PATH}/ssl/server.req \
	&& echo nsComment			= \"OpenSSL Generated Server Certificate\" >> ${JUPYTER_PATH}/ssl/server.req \
	&& echo subjectKeyIdentifier = hash >> ${JUPYTER_PATH}/ssl/server.req \
	&& echo authorityKeyIdentifier = keyid,issuer:always >> ${JUPYTER_PATH}/ssl/server.req \
	&& echo keyUsage = critical, digitalSignature, keyEncipherment >> ${JUPYTER_PATH}/ssl/server.req \
	&& echo extendedKeyUsage	= serverAuth >> ${JUPYTER_PATH}/ssl/server.req \
	&& echo [ req_ext ] >> ${JUPYTER_PATH}/ssl/server.req \
	&& echo subjectAltName		= @alt_names >> ${JUPYTER_PATH}/ssl/server.req \
	&& echo [ alt_names ] >> ${JUPYTER_PATH}/ssl/server.req \
	&& echo DNS.1 = ${HOSTNAME} >> ${JUPYTER_PATH}/ssl/server.req \
	#
	# Creates a new certificate request and private key that is not password protected (-nodes)
	#
	&& openssl req -newkey rsa:2048 -days 3650 -nodes -config ${JUPYTER_PATH}/ssl/server.req \
		-keyout ${JUPYTER_PATH}/ssl/server-key.pem -out ${JUPYTER_PATH}/ssl/server-req.pem \	
	#
	# Process the server key, the key was originally written in PKCS#8 Private-Key Information Syntax Standard
	# and converts it to a PKCS#1 format, an RSA PRIVATE KEY
	#
	&& openssl rsa -in ${JUPYTER_PATH}/ssl/server-key.pem -out ${JUPYTER_PATH}/ssl/server-key.pem \
	&& chmod 0400 ${JUPYTER_PATH}/ssl/server-key.pem \
	#
	# Make sure all environment variables are loaded
	#
	&& source /root/.bashrc \
	&& export PATH=$PATH \
	#
	# Sign the server certificate
	#
	&& openssl x509 -req -in ${JUPYTER_PATH}/ssl/server-req.pem -days 3650 -extfile ${JUPYTER_PATH}/ssl/server.req \
		-extensions server_cert -CA "${CA_CERT}" -CAkey "${CA_KEY}" \
		-passin "pass:${CA_PRIVATE_KEY_PASSWORD}" -set_serial 01 -out ${JUPYTER_PATH}/ssl/server-cert.pem \
	&& chmod 0444 ${JUPYTER_PATH}/ssl/server-cert.pem \
	#
	# Make sure path includes everything for new users
	#
	&& echo "PATH=${PATH}" >> /etc/profile \
	#
	# Add the group and user for running the jupyter services
	#
	&& addgroup --system jupyter \
	#
	# Use -gecos "" to bypass prompts
	#
	&& adduser --system --ingroup jupyter --home /home/jupyter --shell /bin/bash --disabled-password --gecos "" jupyter \
	&& mkdir -p "/home/jupyter/notebooks" \
	&& chown --recursive jupyter "/home/jupyter" \
	#
	# Make sure jupyter user owns the jupyter paths
	#
	&& chown --recursive jupyter:jupyter ${JUPYTER_PATH} \
	&& chown --recursive jupyter:jupyter ${JUPYTER_CONFIG_DIR} \	
	#
	# Delete the config file
	#
	&& rm -f ${JUPYTER_PATH}/ssl/server.req \
	#
	# Delete the signing request
	#
	&& rm -f ${JUPYTER_PATH}/ssl/server-req.pem \
	#
	# Remove unneeded apt packages
	#
	&& apt-get remove --assume-yes wget \
	&& apt-get autoclean -y \
	&& apt-get autoremove -y \
	&& apt-get clean -y \
	&& rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /tmp/entrypoint.sh

EXPOSE 8888 8081

ENTRYPOINT ["/tmp/entrypoint.sh"]